version: '3.1'

services:
  test:
    build:
      context: .
      dockerfile: Docker/Dockerfile.test
    container_name: flask_test
    environment:
      DATABASE_URL: 'sqlite:///:memory:'
      FLASK_APP: run.py
      FLASK_ENV: testing